[project]
name = "elt-with-dlt"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyterlab>=4.2.5",
    "dlt[duckdb]>=1.2.0",
    "streamlit>=1.39.0",
    "lib",
    "marimo>=0.20.4",
]

[tool.uv.sources]
lib = { path = "lib", editable = true }
